### ISSUE TITLE
Create visualization with charts

### ISSUE THREAD

**Issue by lgdeloss** [NCSU-Group7-SE2021/slash#4]

**Comment by vickymhs** [comment]
@kirantejatummuri Can you briefly explain the approach for creating visualization charts through react?

**Comment by kirantejatummuri** [comment]
For a search item provided by the user we should be able to use the Analysis API to fetch the analysis data and represent this in the form of Pie/Line charts. The charts provided by react-charts-2 charting library can be used here.
